select * from oauth_client_details;

insert into oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity ) values('test', 'res1', '$2a$10$ofuJ5MMaxMJGoyQt8mgadOnMk.R6O2aiTsC9fPjhJ8h5z6Zy1cZD.', 'string', 'implicit,password', 'string', 'auth1,auth2', 6000, 6000);
insert into uc_user (name, password, enable, lock, expired) values ('reader', '$2a$10$I9T1dbLiDHFeYXOED5x7Ke5mBGIsdIJ5KC5OPS428DkxwyeAZCKy.', 1, 0, 0);

-- resource data
INSERT INTO oauth_resources (resource_id, name) VALUES('hjjwu', '声流改产持太间多五院利列往证院速商可文那条特众手切。');
INSERT INTO oauth_resources (resource_id, name) VALUES('gbqlog', '为高示作形教许正马六四口志圆引形真产王山规音型求才花达下。');
INSERT INTO oauth_resources (resource_id, name) VALUES('ypytb', '小身团权你做第量关党步花构器圆油听标手西资被位能更共加自众。');
INSERT INTO oauth_resources (resource_id, name) VALUES('hol', '多些提数三土公出证能大元时达特报美。');
INSERT INTO oauth_resources (resource_id, name) VALUES('hrmfzwqa', '料至九建名利常委改却约保才进机系把需带太北起百中子叫支。');
INSERT INTO oauth_resources (resource_id, name) VALUES('bulaqgs', '文那才日点身通化圆团根划红是周队见标复准和生各。');
INSERT INTO oauth_resources (resource_id, name) VALUES('srgwo', '现照料张问北定两下果国所风金性毛属商将步在海料支。');
INSERT INTO oauth_resources (resource_id, name) VALUES('zlcg', '间较江组布年活设等拉议军。');
INSERT INTO oauth_resources (resource_id, name) VALUES('smt', '争识件象号边器高车半结何今难由走效为。');
INSERT INTO oauth_resources (resource_id, name) VALUES('wiewsx', '引百色打气八该导区管接叫无果积区思看。');
INSERT INTO oauth_resources (resource_id, name) VALUES('pvo', '部也定真多面识亲东时处率队运老素识根速结角当打马任大人。');
INSERT INTO oauth_resources (resource_id, name) VALUES('jvcmw', '油适发属写族记制许白派共小切干利来广就易前起。');
INSERT INTO oauth_resources (resource_id, name) VALUES('xjqszivqx', '整气运观持县素复导亲量统科情发名象反近生素适提队电。');
INSERT INTO oauth_resources (resource_id, name) VALUES('htgrhu', '会规已与而子住例周变从半联。');
INSERT INTO oauth_resources (resource_id, name) VALUES('winjeg', '少共广毛把铁农区专些才石京安事院农快战道。');
INSERT INTO oauth_resources (resource_id, name) VALUES('dyzog', '学家通八广设整物信心边别命成为立南我压构导。');
INSERT INTO oauth_resources (resource_id, name) VALUES('ghjwyb', '后从亲由别步且周军认即七。');
INSERT INTO oauth_resources (resource_id, name) VALUES('xihawuhmz', '战构队法比议等界位话报消王省派率还指物。');
INSERT INTO oauth_resources (resource_id, name) VALUES('kkmh', '型全给点除界国作管养划。');
INSERT INTO oauth_resources (resource_id, name) VALUES('gwmmgzzeio', '治整马安她术识照三何风几空统前把许求安最。');
INSERT INTO oauth_resources (resource_id, name) VALUES('ppbyhkwfo', '层向作后支口真题它支给时情里近合状持义低据再加越百元定等两。');
INSERT INTO oauth_resources (resource_id, name) VALUES('xswliemkia', '调院要场向定交从共风备根者重九器红打都所因下了节长拉阶。');
INSERT INTO oauth_resources (resource_id, name) VALUES('wqhk', '造六还全由至风机利自石装问红。');
INSERT INTO oauth_resources (resource_id, name) VALUES('ztvuffg', '直文活条须边总小务并江国交没收再表常。');
INSERT INTO oauth_resources (resource_id, name) VALUES('xocjhvyn', '京米金维数机对强装务例等照别结面水因示直至。');
INSERT INTO oauth_resources (resource_id, name) VALUES('kwkadyx', '水列感机维她习除么例九会。');
INSERT INTO oauth_resources (resource_id, name) VALUES('lehpwahm', '系利完出十值同放林联称。');
INSERT INTO oauth_resources (resource_id, name) VALUES('eto', '革角等总北具观养阶公利。');
INSERT INTO oauth_resources (resource_id, name) VALUES('xcuicoap', '部论老周准己此他例三细少连照查效龙间些人转大。');
INSERT INTO oauth_resources (resource_id, name) VALUES('zofnrjqyq', '容被感美往算打战自任社准斯立做报张指带者必总建听张山。');
INSERT INTO oauth_resources (resource_id, name) VALUES('dhg', '器响应转深许角族立机整格复线红整维又。');


-- scopes data
INSERT INTO oauth_scopes (scope_id, name) VALUES('vnxtntznu', '写机省为那加应积成重济解则候质切花广最给。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('gwrw', '众长除听设果何现又易被拉经可把革是万标转价加难制复去须。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('vdbte', '温压制表需王么种群已给区电机间律。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('smqlk', '真太多无毛带论市战广量名示志济什得细可直各斯入。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('ycmmfkhigl', '报成己色器切集亲花科意深看大美心色放准六只确铁。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('rvhs', '类治权可三较低就体对斗低来因水比老业着论今门北将金。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('wtqdod', '头老成儿众元于开务别很产可同角片点素我除育那性车。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('trxgytc', '起能马七办将么委置用达成持己百技机了教决龙去性会解林结用。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('kpzdvpj', '指法什养米部其组经我间技。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('bwprqzg', '织约听厂重解约员史广共却很。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('efdbijgtq', '百重争低除量再积论广铁交相确主及是装门省。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('cnw', '方意整资火并器系级与月号和置历今院具代。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('ppvobopu', '利难工证关织个变写采改常月下标片应民持认于流领委。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('nomdzo', '细基基很点图值层六也应七院主次何向此政。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('kqbpi', '受品南必也把上验民想带青查下取问阶面心体。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('ijcmkl', '这米技引五话之持传周造比你照花基学政律方名包石该使科打。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('lbgav', '白日民四义员且总反性治。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('etpnnshd', '只国性置济之公花体状保。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('nrivyqsg', '真身将太色非联西须特原习则果口重正式电复选关质千西时往。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('xtvlfyqwz', '四省着质信处等管么才阶约收议争科业照主解比事划开到。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('bgmfzs', '如原府品千级打个共族般连委下按热。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('esfrsp', '马总近许接造流无引到水准群关满识须论公研由。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('hrenzbth', '百已从低者次人展科育放门快利广前今理算领带报查千育里求住。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('gcdj', '可思于她出现造达支达离战集并面性许料料毛身也。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('gwxrzgjgu', '作加消量最造却平口了红反下族同条革名非效按称。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('qtik', '天文常门眼即得也事非集米报管县长老场书理管门白十来象低效。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('asbirl', '专县色些却头群已口总他此海本千清高查展京光定系。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('hdylmcltn', '关些能再主共期运达安劳用压表就亲边水想合要有步见历。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('kzrfzdvfmt', '重次千置再记复亲界共成达什起。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('tvdtrwips', '学除常亲到支争性命消写重光级正。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('kehgboz', '到算物计口叫快算维设最族装。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('wmdnwml', '导用格或质达车清已别增周南增调下门方去车年日四对西西把立。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('fsrni', '引叫权且高当细出维难土或眼自选养二接样拉装最合战别公传具声。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('ozves', '断厂识论十精因并话社队如。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('jjkkbw', '数感知任别应平持军市。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('ahmwkta', '圆温对人志事拉则年动地农离果本求作。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('stpipup', '少快件完照达活都和感层马题事反声好做以属斯国现具权。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('psjegxyq', '西些外动得四分力实证号天广定龙建地受下器你两期其参。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('jiunqeqxim', '经说两记花查干除八手任称观还必没色指这改提包系。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('yticktj', '压较太都参品子单本酸极入知子权酸和变次常如。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('obdjm', '会场无每接住何造除非就体人。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('eryrqmm', '改身原极济是商决率改习效方空农各识但广什白强消参。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('axrcvss', '叫属代并圆外技主素节金山位知们社南。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('cubcnouovr', '件书东置定月温料族在后。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('yuhup', '角包研领书设更增界将器外认列整好省权深。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('rfbneyrx', '量且据决老存权却系儿感将专光调从正格边火素查。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('rojyd', '中规识老又精去带重往温支太支连主也权率权两约历入油。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('mplljv', '世点权委资际合分状观数得本。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('zejjdsawq', '志易必已过示受十认处今先选构标住做想受族百然。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('awghgttz', '油同么五总金人式位山步证节准。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('jrlvmc', '论万常酸铁拉派直写管政强六要马没叫再名把特识党。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('kysn', '号规条派识情龙角海油带其反京低阶一革代为。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('tkjhdurj', '起易石交众外打加常济节类育极界区办。');
INSERT INTO oauth_scopes (scope_id, name) VALUES('olbc', '七十们次合线具民会据导确教府。');


-- role data
INSERT INTO uc_role (name, desc) VALUES('fwvvifu', '中提调区行石你包济到活离府说它日消全电体性被改亲军识现照金白。');
INSERT INTO uc_role (name, desc) VALUES('ipbxub', '证必府书量候义说者利管米县方。');
INSERT INTO uc_role (name, desc) VALUES('lnvcntsd', '马队队万只太往类深产难力。');
INSERT INTO uc_role (name, desc) VALUES('uwqenfwg', '人点场太能只干技本手重连度题照程层三花利保参组干图己四。');
INSERT INTO uc_role (name, desc) VALUES('rjlrshnhik', '入信了特满体少志没个别回管回量所格东光五队水几管不。');
INSERT INTO uc_role (name, desc) VALUES('ebkbiquv', '形系常口红很把区专离来到构小满边革书响区立图五入体运。');
INSERT INTO uc_role (name, desc) VALUES('smctjtwo', '共斯从三天题业酸根满委认门方见研间化算还质你电当日即价对又比。');
INSERT INTO uc_role (name, desc) VALUES('jrpaw', '清美话派机济族天所建先般。');
INSERT INTO uc_role (name, desc) VALUES('edvdsrg', '解广单员备程样低成两在求接后白正手采音习听力复世调立做社十。');
INSERT INTO uc_role (name, desc) VALUES('ilehqwtn', '通县统合例革领具战太复全业即边白位或物事响毛管五战体指。');
INSERT INTO uc_role (name, desc) VALUES('zmpwagd', '县六许存东存化铁很领般。');
INSERT INTO uc_role (name, desc) VALUES('xngtgd', '信般说育合它候又问阶照统问气统。');
INSERT INTO uc_role (name, desc) VALUES('rwsi', '行所率口国打每无于标质存事前易而安被质民马没即被断团细结。');
INSERT INTO uc_role (name, desc) VALUES('rjr', '红具性向七严自名还九美易下元两几际各采院完件安实重。');
INSERT INTO uc_role (name, desc) VALUES('vnfw', '老压队深被制月战真专应但院叫法入需的。');
INSERT INTO uc_role (name, desc) VALUES('ycox', '议包思权斯毛做部每较低选四格相。');
INSERT INTO uc_role (name, desc) VALUES('bwi', '识证低干存平所美决任外更美按声非到美石于了根圆南商交从是山。');
INSERT INTO uc_role (name, desc) VALUES('azpr', '义九回消通需一结资地此县被生何争难情品存石办省消就些太圆。');
INSERT INTO uc_role (name, desc) VALUES('galp', '断安有求规极直小易白目确月维中思因酸类写只。');
INSERT INTO uc_role (name, desc) VALUES('xoeucnioyo', '交行压用场九养米发精世务酸确。');
INSERT INTO uc_role (name, desc) VALUES('jhfpiw', '见活角世强专别特改四已本得改解验照反水断教进实满主。');
INSERT INTO uc_role (name, desc) VALUES('kkqjbzhkvo', '准需节子并属再细次活但段资起集。');
INSERT INTO uc_role (name, desc) VALUES('wypo', '严报才种白又集对油深道常技。');
INSERT INTO uc_role (name, desc) VALUES('gnhiiidga', '家件解带合治得报情列矿。');
INSERT INTO uc_role (name, desc) VALUES('pyluwsj', '型队或土整各之度通列步东温家联米育期。');
INSERT INTO uc_role (name, desc) VALUES('lgmoqppxe', '满战学拉备严实龙火种门者思。');
INSERT INTO uc_role (name, desc) VALUES('nxphi', '九次号办圆形约该更称连感。');